### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by hugok79** [discord/discord-intl#11]
@faultyserver Hello, I see that Discord supports several languages and so I would like to know where Discord's language translation is done. I'd like to help with the translation in particular with the `Portuguese` spoken in **Portugal**. Currently I see that only Portuguese (Brazil) is supported, but I refuse to use it as it is a variant of Portuguese that is increasingly moving away from the Portuguese language with misspelled and invented words.

**Comment by faultyserver** [comment]
Discord manages translation content through a set of professional vendors and is not open for external language contributions. This project is open-sourced as the underlying system that powers _managing_ those translations, for version control, bundling into applications, linting for quality, and querying as needed.

Requests for additional languages to be supported are best done through the support forums.
